on: [push, pull_request]
name: Golint
jobs:
  s3upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: |
          go get -u golang.org/x/lint/golint

      - name: Run vet & lint
        run: |
          cd s3upload
          go vet .
          ls
          golint -set_exit_status . 

  dynamoUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: |
          go get -u golang.org/x/lint/golint

      - name: Run vet & lint
        run: |
          cd dynamoUpload
          go vet .
          ls
          golint -set_exit_status . 


